import type { LucideIcon } from 'lucide-react'
import {
  LayoutDashboardIcon,
  BotMessageSquareIcon,
  RouteIcon,
  FileTextIcon,
  MailIcon,
  BriefcaseIcon,
  TrophyIcon,
  SettingsIcon,
  PlusIcon,
  PlusCircleIcon,
  XIcon,
  CheckIcon,
  SearchIcon,
  MenuIcon,
  EllipsisIcon,
  PencilIcon,
  Trash2Icon,
  DownloadIcon,
  UploadIcon,
  CopyIcon,
  ExternalLinkIcon,
  SendIcon,
  FilterIcon,
  RefreshCwIcon,
  ChevronRightIcon,
  ChevronLeftIcon,
  ChevronDownIcon,
  ChevronUpIcon,
  ArrowRightIcon,
  ArrowLeftIcon,
  ArrowUpRightIcon,
  CircleCheckIcon,
  TriangleAlertIcon,
  CircleXIcon,
  InfoIcon,
  SparklesIcon,
  Loader2Icon,
  LockIcon,
  BellIcon,
  CircleHelpIcon,
  SunIcon,
  MoonIcon,
  MonitorIcon,
  UserIcon,
  CircleUserRoundIcon,
  VenusIcon,
  MarsIcon,
  LogOutIcon,
  LogInIcon,
  TargetIcon,
  FlameIcon,
  CalendarIcon,
  ClockIcon,
  StarIcon,
  ZapIcon,
  TrendingUpIcon,
  TrendingDownIcon,
  GraduationCapIcon,
  MessageCircleIcon,
  EyeIcon,
  PlayIcon,
  PauseIcon,
  CircleIcon,
  PanelLeftIcon,
  HouseIcon,
} from 'lucide-react'

/**
 * Curated icon registry. Icons are statically imported (so they tree-shake) and
 * addressed by a stable semantic name, decoupling call sites from the
 * underlying Lucide export names. Add new icons here — never import Lucide
 * directly in feature code.
 */
export const iconRegistry = {
  // Navigation
  dashboard: LayoutDashboardIcon,
  coach: BotMessageSquareIcon,
  /** STUB — the roadmap is planned, not built (PRODUCT.md, "Planned"). Kept so
   *  the icon choice survives the gap; no call site should use it until then. */
  roadmap: RouteIcon,
  resume: FileTextIcon,
  'cover-letter': MailIcon,
  applications: BriefcaseIcon,
  achievements: TrophyIcon,
  settings: SettingsIcon,
  home: HouseIcon,

  // Actions
  add: PlusIcon,
  'add-circle': PlusCircleIcon,
  close: XIcon,
  check: CheckIcon,
  search: SearchIcon,
  menu: MenuIcon,
  more: EllipsisIcon,
  edit: PencilIcon,
  delete: Trash2Icon,
  download: DownloadIcon,
  upload: UploadIcon,
  copy: CopyIcon,
  external: ExternalLinkIcon,
  send: SendIcon,
  filter: FilterIcon,
  refresh: RefreshCwIcon,

  // Directional
  'chevron-right': ChevronRightIcon,
  'chevron-left': ChevronLeftIcon,
  'chevron-down': ChevronDownIcon,
  'chevron-up': ChevronUpIcon,
  'arrow-right': ArrowRightIcon,
  'arrow-left': ArrowLeftIcon,
  'arrow-up-right': ArrowUpRightIcon,

  // Feedback / status
  success: CircleCheckIcon,
  warning: TriangleAlertIcon,
  error: CircleXIcon,
  info: InfoIcon,
  sparkles: SparklesIcon,
  loader: Loader2Icon,
  lock: LockIcon,
  bell: BellIcon,
  help: CircleHelpIcon,

  // Theme
  sun: SunIcon,
  moon: MoonIcon,
  system: MonitorIcon,

  // Account
  user: UserIcon,
  'user-neutral': CircleUserRoundIcon,
  'user-woman': VenusIcon,
  'user-man': MarsIcon,
  logout: LogOutIcon,
  login: LogInIcon,

  // Domain
  target: TargetIcon,
  streak: FlameIcon,
  calendar: CalendarIcon,
  clock: ClockIcon,
  star: StarIcon,
  zap: ZapIcon,
  trending: TrendingUpIcon,
  'trending-down': TrendingDownIcon,
  learning: GraduationCapIcon,
  message: MessageCircleIcon,
  preview: EyeIcon,
  play: PlayIcon,
  pause: PauseIcon,
  circle: CircleIcon,
  'panel-left': PanelLeftIcon,
} satisfies Record<string, LucideIcon>

export type IconName = keyof typeof iconRegistry
