/**
 * Token generator — projects lib/design/tokens.ts into CSS.
 *
 * Emits two committed, never-hand-edited files:
 *   src/styles/tokens.generated.css  — the :root / .dark custom-property layer
 *   src/styles/theme.generated.css   — the Tailwind v4 `@theme inline` mapping
 *
 * Colors are emitted in OKLCH (perceptually uniform, P3-ready). Before writing,
 * a WCAG-AA contrast gate checks the key text/surface pairs in BOTH themes
 * (compositing translucent surfaces over the page background) and FAILS the
 * build on any violation — the palette is provably accessible or it doesn't ship.
 *
 * Run with: `npm run tokens` (also runs on predev / prebuild). Node native TS.
 */
import { writeFileSync } from 'node:fs'
import { join } from 'node:path'

import { converter, wcagContrast, type Rgb } from 'culori'

import {
  palette,
  semanticColors,
  radiusBase,
  radius,
  shadow,
  motion,
  zIndex,
  layout,
  type SemanticColorRole,
} from '../src/lib/design/tokens.ts'

const toOklch = converter('oklch')
const toRgb = converter('rgb')

const round = (n: number, d: number) => Number(n.toFixed(d))

/* ------------------------------- OKLCH output ------------------------------ */

function oklchStr(value: string): string {
  const c = toOklch(value)
  if (!c) return value
  const l = round(c.l, 4)
  const chroma = round(c.c, 4)
  const h = c.h == null || Number.isNaN(c.h) ? 0 : round(c.h, 2)
  const a = c.alpha ?? 1
  return a < 1 ? `oklch(${l} ${chroma} ${h} / ${round(a, 3)})` : `oklch(${l} ${chroma} ${h})`
}

/* ------------------------------ Contrast gate ------------------------------ */

const WHITE: Rgb = { mode: 'rgb', r: 1, g: 1, b: 1 }

function compositeOver(value: string, over: Rgb): Rgb {
  const c = toRgb(value)
  if (!c) return over
  const a = c.alpha ?? 1
  if (a >= 1) return { mode: 'rgb', r: c.r, g: c.g, b: c.b }
  return {
    mode: 'rgb',
    r: a * c.r + (1 - a) * over.r,
    g: a * c.g + (1 - a) * over.g,
    b: a * c.b + (1 - a) * over.b,
  }
}

function contrastRatio(fg: string, bg: string, pageBg: string): number {
  const base = compositeOver(pageBg, WHITE)
  const bgRgb = compositeOver(bg, base)
  const fgRgb = compositeOver(fg, bgRgb)
  return wcagContrast(fgRgb, bgRgb)
}

/** [foreground role, background role, minimum ratio]. */
const CONTRAST_PAIRS: [SemanticColorRole, SemanticColorRole, number][] = [
  ['foreground', 'background', 4.5],
  ['foreground', 'card', 4.5],
  ['foreground', 'muted', 4.5],
  ['muted-foreground', 'background', 4.5],
  ['muted-foreground', 'card', 4.5],
  ['muted-foreground', 'muted', 4.5],
  ['card-foreground', 'card', 4.5],
  ['popover-foreground', 'popover', 4.5],
  ['secondary-foreground', 'secondary', 4.5],
  ['accent-foreground', 'accent', 4.5],
  ['sidebar-foreground', 'sidebar', 4.5],
  ['sidebar-accent-foreground', 'sidebar-accent', 4.5],
  ['primary-foreground', 'primary', 4.5],
  ['brand', 'background', 4.5],
  ['brand', 'card', 4.5],
  ['brand', 'brand-muted', 4.5],
  ['success', 'success-muted', 4.5],
  ['warning', 'warning-muted', 4.5],
  ['info', 'info-muted', 4.5],
  ['destructive', 'destructive-muted', 4.5],
]

function auditContrast(): string[] {
  const failures: string[] = []
  for (const mode of ['light', 'dark'] as const) {
    const colors = semanticColors[mode]
    for (const [fg, bg, min] of CONTRAST_PAIRS) {
      const ratio = contrastRatio(colors[fg], colors[bg], colors.background)
      if (ratio + 0.005 < min) {
        failures.push(`  ✗ [${mode}] ${fg} on ${bg} — ${round(ratio, 2)}:1 (needs ${min}:1)`)
      }
    }
  }
  return failures
}

/* --------------------------- tokens.generated.css -------------------------- */

const INDENT = '  '
const block = (lines: string[]): string => lines.map((l) => INDENT + l).join('\n')

const OUT_DIR = join(import.meta.dirname, '..', 'src', 'styles')

const paletteVars = (): string[] =>
  Object.entries(palette).flatMap(([group, shades]) =>
    Object.entries(shades).map(([shade, value]) => `--${group}-${shade}: ${oklchStr(value)};`),
  )

const roleVars = (map: Record<string, string>): string[] =>
  Object.entries(map).map(([role, value]) => `--${role}: ${oklchStr(value)};`)

const shadowVars = (map: Record<string, string>): string[] =>
  Object.entries(map).map(([key, value]) => `--shadow-${key}: ${value};`)

const scaleVars = (): string[] => [
  `--radius: ${radiusBase};`,
  `--radius-full: ${radius.full};`,
  ...Object.entries(motion.duration).map(([k, v]) => `--duration-${k}: ${v};`),
  ...Object.entries(motion.easing).map(([k, v]) => `--ease-${k}: ${v};`),
  ...Object.entries(zIndex).map(([k, v]) => `--z-${k}: ${v};`),
  ...Object.entries(layout).map(([k, v]) => `--${k}: ${v};`),
]

const tokensCss = `/**
 * AUTO-GENERATED by scripts/build-tokens.mts — DO NOT EDIT.
 * Edit lib/design/tokens.ts then run \`npm run tokens\`. Colors are OKLCH and
 * pass a WCAG-AA contrast gate (enforced at build time).
 */

:root {
  /* Palette ramps */
${block(paletteVars())}

  /* Semantic roles — light */
${block(roleVars(semanticColors.light))}

  /* Scales */
${block(scaleVars())}

  /* Elevation — light */
${block(shadowVars(shadow.light))}
}

.dark {
  /* Semantic roles — dark */
${block(roleVars(semanticColors.dark))}

  /* Elevation — dark */
${block(shadowVars(shadow.dark))}
}
`

/* ---------------------------- theme.generated.css -------------------------- */

const semanticThemeVars = (): string[] =>
  Object.keys(semanticColors.light).map((role) => `--color-${role}: var(--${role});`)

const paletteThemeVars = (): string[] =>
  Object.entries(palette).flatMap(([group, shades]) =>
    Object.keys(shades).map((shade) => `--color-${group}-${shade}: var(--${group}-${shade});`),
  )

const shadowThemeVars = (): string[] =>
  Object.keys(shadow.light).map((k) => `--shadow-${k}: var(--shadow-${k});`)

const easeThemeVars = (): string[] =>
  Object.keys(motion.easing).map((k) => `--ease-${k}: var(--ease-${k});`)

const themeCss = `/**
 * AUTO-GENERATED by scripts/build-tokens.mts — DO NOT EDIT.
 * Tailwind v4 theme mapping: every design token exposed as a utility.
 */

@theme inline {
  /* Typography */
  --font-sans: var(--font-sans);
  --font-mono: var(--font-mono);
  --font-heading: var(--font-heading);

  /* Radius scale — derived from the base --radius */
  --radius-xs: calc(var(--radius) * 0.5);
  --radius-sm: calc(var(--radius) * 0.7);
  --radius-md: calc(var(--radius) * 0.85);
  --radius-lg: var(--radius);
  --radius-xl: calc(var(--radius) * 1.35);
  --radius-2xl: calc(var(--radius) * 1.85);
  --radius-3xl: calc(var(--radius) * 2.4);

  /* Semantic colors */
${block(semanticThemeVars())}

  /* Palette ramps */
${block(paletteThemeVars())}

  /* Elevation */
${block(shadowThemeVars())}

  /* Easing */
${block(easeThemeVars())}
}
`

/* -------------------------------- write ------------------------------------ */

const failures = auditContrast()
if (failures.length > 0) {
  console.error(`\n✗ Contrast gate failed (${failures.length} pair(s) below WCAG AA):`)
  console.error(failures.join('\n'))
  console.error('\nFix the values in src/lib/design/tokens.ts and re-run.\n')
  process.exit(1)
}

writeFileSync(join(OUT_DIR, 'tokens.generated.css'), tokensCss, 'utf8')
writeFileSync(join(OUT_DIR, 'theme.generated.css'), themeCss, 'utf8')
console.log(
  `✓ tokens written in OKLCH; contrast gate passed (${CONTRAST_PAIRS.length} pairs × 2 themes)`,
)
